import type { Anime, AnimeRecommendation } from '@/types/anime';

export const mockAnimeData: Anime[] = [
  {
    id: '1',
    title: 'Attack on Titan',
    coverImage: 'https://picsum.photos/seed/aot/300/450',
    bannerImage: 'https://picsum.photos/seed/aot-banner/1200/400',
    year: 2013,
    genre: ['Action', 'Dark Fantasy', 'Post-apocalyptic'],
    status: 'Completed',
    synopsis: 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.',
    averageRating: 4.8,
    type: 'TV',
  },
  {
    id: '2',
    title: 'Jujutsu Kaisen',
    coverImage: 'https://picsum.photos/seed/jjk/300/450',
    bannerImage: 'https://picsum.photos/seed/jjk-banner/1200/400',
    year: 2020,
    genre: ['Supernatural', 'Dark Fantasy', 'Action'],
    status: 'Ongoing',
    synopsis: 'A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman\'s school to be able to locate the demon\'s other body parts and thus exorcise himself.',
    averageRating: 4.7,
    type: 'TV',
  },
  {
    id: '3',
    title: 'Demon Slayer: Kimetsu no Yaiba',
    coverImage: 'https://picsum.photos/seed/ds/300/450',
    bannerImage: 'https://picsum.photos/seed/ds-banner/1200/400',
    year: 2019,
    genre: ['Dark Fantasy', 'Adventure', 'Action'],
    status: 'Ongoing',
    synopsis: 'A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko, who is turning into a demon slowly. Tanjiro sets out to become a demon slayer to avenge his family and cure his sister.',
    averageRating: 4.9,
    type: 'TV',
  },
  {
    id: '4',
    title: 'Spy x Family',
    coverImage: 'https://picsum.photos/seed/spyxfamily/300/450',
    bannerImage: 'https://picsum.photos/seed/spyxfamily-banner/1200/400',
    year: 2022,
    genre: ['Comedy', 'Action', 'Spy Fiction'],
    status: 'Ongoing',
    synopsis: 'A spy on an undercover mission gets married and adopts a child, not realizing that his fake wife is an assassin and his fake daughter is a telepath.',
    averageRating: 4.6,
    type: 'TV',
  },
  {
    id: '5',
    title: 'Chainsaw Man',
    coverImage: 'https://picsum.photos/seed/csm/300/450',
    bannerImage: 'https://picsum.photos/seed/csm-banner/1200/400',
    year: 2022,
    genre: ['Action', 'Dark Fantasy', 'Comedy Horror'],
    status: 'Ongoing',
    synopsis: 'Following a betrayal, a young man left for dead is reborn as a Devil-Human hybrid after merging with his pet devil and is soon enlisted into an organisation dedicated to hunting devils.',
    averageRating: 4.5,
    type: 'TV',
  },
  {
    id: '6',
    title: 'Your Name. (Kimi no Na wa.)',
    coverImage: 'https://picsum.photos/seed/yourname/300/450',
    bannerImage: 'https://picsum.photos/seed/yourname-banner/1200/400',
    year: 2016,
    genre: ['Romance', 'Fantasy', 'Drama'],
    status: 'Completed',
    synopsis: 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?',
    averageRating: 4.9,
    type: 'Movie',
  },
   {
    id: '7',
    title: 'Solo Leveling',
    coverImage: 'https://picsum.photos/seed/sololeveling/300/450',
    bannerImage: 'https://picsum.photos/seed/sololeveling-banner/1200/400',
    year: 2024,
    genre: ['Action', 'Fantasy', 'Adventure'],
    status: 'Ongoing',
    synopsis: 'In a world where hunters with magical abilities battle deadly monsters to protect humanity, a notoriously weak hunter Jinwoo Sung finds himself in a relentless struggle for survival.',
    averageRating: 4.8,
    type: 'TV',
  },
  {
    id: '8',
    title: 'Frieren: Beyond Journey\'s End',
    coverImage: 'https://picsum.photos/seed/frieren/300/450',
    bannerImage: 'https://picsum.photos/seed/frieren-banner/1200/400',
    year: 2023,
    genre: ['Adventure', 'Fantasy', 'Drama'],
    status: 'Ongoing',
    synopsis: 'After the party of heroes defeats the Demon King, they disband. Frieren, the elf mage, outlives her companions and embarks on a new journey to understand life and humanity.',
    averageRating: 4.9,
    type: 'TV',
  },
];

export const mockRecommendations: AnimeRecommendation[] = [
  {
    id: '1',
    title: 'Vinland Saga',
    coverImage: 'https://picsum.photos/seed/vinland/300/450',
    reason: 'Since you liked Attack on Titan, you might enjoy its historical themes and intense action.',
  },
  {
    id: '2',
    title: 'Death Note',
    coverImage: 'https://picsum.photos/seed/deathnote/300/450',
    reason: 'If you enjoyed the dark fantasy and strategic elements of Jujutsu Kaisen.',
  },
  {
    id: '3',
    title: 'Fullmetal Alchemist: Brotherhood',
    coverImage: 'https://picsum.photos/seed/fmab/300/450',
    reason: 'A classic adventure with deep themes, similar to Demon Slayer.',
  },
];
